regression: Skip 072 if the Git version is too old
Teach run-tests that exit code 77 means the test was skipped.  This
counts as success, but does not compare the output with the expected
output.

The t-072.sh script exits with code 77 if run with a version of git
prior to 2.31.0.  Version 2.31.0 is the first where the submodule
support works with guilt.

Document that it is safe to use the "-b" option to "git init" in
t-072.sh.

Signed-off-by: Per Cederqvist <ceder@lysator.liu.se>

diff --git a/regression/run-tests b/regression/run-tests
--- a/regression/run-tests
+++ b/regression/run-tests
@@ -61,18 +61,25 @@ function run_test
 
 	# run the test
 	cd "$REPODIR" > /dev/null
-	if "$REG_DIR/t-$1.sh" 2>&1 > "$LOGFILE"; then
-		ERR=false
-	else
-		ERR=true
-	fi
+	set +e
+	"$REG_DIR/t-$1.sh" 2>&1 > "$LOGFILE"
+	rv=$?
+	set -e
 
 	cd - > /dev/null
 
-	$ERR && test_failed
-	diff -u "t-$1.out" "$LOGFILE" || test_failed
-
-	echo "done."
+	case $rv in
+		0)
+			diff -u "t-$1.out" "$LOGFILE" || test_failed
+			echo "done."
+			;;
+		77)
+			echo "skipped."
+			;;
+		*)
+			test_failed
+			;;
+	esac
 
 	rm -rf "$REPODIR" "$LOGFILE"
 }
